config/routes.rb
Rails.application.routes.draw do

  devise_for :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount ActionCable.server => '/cable'

  resources :projects do
    collection do
      get 'archived'
    end
    member do
      post 'add_member'
      post 'remove_member'
    end
  end
  
  resources :members do
    member do
      post 'lock'
      get 'qualification'
    end
    collection do
      patch 'update_password'
      get 'public'
      get 'departments'
      get 'annotations'
      get 'qualifications'
    end
  end

  resources :annotations
  resources :inquiries
  resources :people

  resources :fee_payments do
    collection do
      get 'reset_all'
      delete 'reset_all'
      post 'email'
    end
  end

  resources :courses do
    member do
      post 'email'
      post 'add_member/:member_id', to: 'courses#add_member', as: :add_member_to
      post 'remove_member/:member_id', to: 'courses#remove_member', as: :remove_member_from
    end
  end

  resources :consultations do
    member do
      post 'email'
    end
  end

  resources :bibliographies do
    resources :documents do
      member do
        get 'get_attachment'
        get 'thumbnail'
      end
    end
  end

  resources :events do
    collection do
      #get 'index'
      get 'export', defaults: { format: 'ics' }
      get 'calendar'
    end
    member do
      post 'add_member/:member_id', to: 'events#add_member', as: :add_member_to
      post 'remove_member/:member_id', to: 'events#remove_member', as: :remove_member_from

      patch 'attend', to: 'events#attend'
      patch 'unattend', to: 'events#unattend'
      post 'email'
    end
  end

  patch 'attendances/:id/permit', to: 'attendances#permit', as: :permit_attendance
  patch 'attendances/:id/unpermit', to: 'attendances#unpermit', as: :unpermit_attendance
  patch 'attendances/:id/award', to: 'attendances#award', as: :award_attendance
  patch 'attendances/:id/unaward', to: 'attendances#unaward', as: :unaward_attendance


  resources :tasks do
    collection do
      get 'done'
    end
    member do
      post 'close'
    end
  end

  get 'public_mandates', to: 'mandates#public_index', as: :public_mandates
  get 'public_people', to: 'people#public_index', as: :public_people
  get 'suggest_person', to: 'people#suggest', as: :suggest_person
  get 'suggest_member', to: 'members#suggest', as: :suggest_member

  get 'rights', to: 'members#index_rights', as: :members_rights
  get 'rights/:id/edit', to: 'members#edit_right', as: :edit_member_right
  patch 'rights/:id', to: 'members#update_right', as: :update_member_right

  resources :conversations do
    resources :messages, only: :create do
      get 'get_attachment'
      get 'thread'
    end
  end

  resources :mandates do
    resources :assignments, only: [:update, :destroy]
    patch 'apply', to: 'assignments#apply'
    patch 'unapply', to: 'assignments#unapply'
    member do
      post 'request_review'
      get 'get_attachment'
      post 'add_member/:member_id', to: 'mandates#add_member'
    end
  end
  get 'window', to: 'window#home', as: :window
  get 'window/detail/:access_code', to: 'window#detail', as: :window_detail
  post 'window/message', to: 'window#message', as: :window_message

  get 'departments/:id', to: 'departments#show', as: :departments # TODO is this still in use?

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :assigned_member, class_name: "Member", foreign_key: 'assigned_member_id', optional: true
	belongs_to :member
	belongs_to :mandate, optional: true

	attr_accessor :deadline_string
	validate :deadline_format
	def deadline_format
		unless deadline_string.blank?
			begin
				self.deadline = Date.parse(deadline_string)
			rescue
				errors.add(:deadline, :invalid)
			end
		end
	end

	validates :title, presence: true

	default_scope { order(created_at: :desc) }

	scope :done, -> { unscoped.where(done: true).order(updated_at: :desc) }
	scope :undone, -> { where(done: false) }

	scope :by_member_and_assignd_to, lambda { |member|
		where("member_id = #{member.id} OR assigned_member_id = #{member.id}")
	}
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  load_and_authorize_resource 
  before_action :load_task, only: [:close, :update, :edit]

  def new
    @task = Task.new
  end

  def done
    if params[:filter]
      @tasks = Task.done.where(mandate_id: params[:filter][:mandate_id]) if params[:filter][:mandate_id]
      @tasks = Task.done.where(department_id: params[:filter][:department_id]) if params[:filter][:department_id]
    else
      @tasks = Task.done.by_member_and_assignd_to current_member
    end
  end

  def index
    if params[:origin]
      @origin = params[:origin]
    elsif request.referer
      @origin = URI(request.referer).path
    end
    
    if params[:filter]
      @tasks = Task.undone.where(mandate_id: params[:filter][:mandate_id]) if params[:filter][:mandate_id]
      @tasks = Task.undone.where(department_id: params[:filter][:department_id]) if params[:filter][:department_id]
    else
      @tasks = Task.undone.by_member_and_assignd_to current_member
    end

    if request.format == :htmlp
      render partial: "listing", formats: [:html], locals: {tasks: @tasks}, layout: false
    else
      redirect_to root_path, notice: 'Aufgabe wurde erfolgreich hinzugefügt.'
    end
  end

  def close
  	@task.update({done: true})
  	index
  end

  def create
    @task = current_member.tasks.new(task_params)
    if @task.save
    	index
    else
      render action: 'new'
    end
  end

  def update
    if @task.update(task_params)
      notice = 'Änderungen an Aufgabe gespeichert.'
      if params[:origin]
        redirect_to params[:origin], notice: notice
      else
        redirect_back(
          notice: notice,
          fallback_location: root_url
        )
      end
    else
      render action: 'edit'
    end
  end

  def edit

  end

  private
    def load_task
        @task = Task.find(params[:id])
    end
		def task_params
      if params[:task][:assigned_member_id] && params[:task][:assigned_member_id] == current_member.id.to_s
        params[:task][:assigned_member_id] = nil
      end
	    params.require(:task).permit(:title, :mandate_id, :department_id, :deadline_string, :assigned_member_id)
  	end

end

app/views/tasks/_form.html.erb
<%= render "common/validation_msg_box", resource: task %>

<%= form_for task do |f| %>
  <% if params[:origin] %>
    <%= hidden_field_tag "origin", params[:origin] %>
  <% end -%>
	<div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :titel %>
        <%= f.text_field :title, class:"form-control" %>
      </div>

      <div class="form-group">
        <label>Ausführung durch anderes Mitglied</label>
        <%= f.hidden_field :assigned_member_id, class:"form-control" %>
        <%= render "members/suggest", target_html_id: "task_assigned_member_id", target_member: task.assigned_member, mandate_id: task.mandate_id %>
      </div>

      <div class="form-group">
        <%= f.label :deadline %> <small class="text-muted">Format: 01.01.2017</small> 
        <%= f.text_field :deadline_string, value: task.deadline ? task.deadline.strftime("%d.%m.%Y") : "", class:"form-control", data: { date_autoclose:"true", provide:"datepicker", date_format:"dd.mm.yyyy" } %>
    

      </div>
  	  <%= f.submit "Speichern", class: "btn btn-primary" %>

    </div>
  </div>
<% end %>

app/views/tasks/_listing.html.erb
<ul class="list-group list-group-flush" id="tasks_listing">
	<% if !tasks.blank? %>
		<% for task in tasks %>
			<% can_manage = can? :manage, task %>
			<li class="list-group-item list-group-item-action flex-column align-items-start task">
				<div class="d-flex w-100 justify-content-between">
					<small>
						<span class="text-primary"><%= task.member.first_name %></span>
						<%= " in " + task.mandate.title if task.mandate %>
						<%= " in " + DEPARTMENT_TITLES[task.department_id] if task.department_id %>
						<span class="text-danger"><%= " an " + task.assigned_member.first_name if task.assigned_member %></span>	
					</small>
					<small class="ml-auto">
						<% if task.deadline %>
							<span class="oi oi-clock mr-1 text-danger"></span> <%= task.deadline.strftime("%d.%m.%Y") %>
						<% elsif can_manage and task.done == false %>
							<input data-date-autoclose="true" data-date-format="dd.mm.yyyy" autocomplete="off" data-provide="datepicker" placeholder="Deadline" style="text-align:right; border:none; background: none; padding:0px; width:70px; cursor:pointer; font-family: inherit;" onchange="set_deadline(this)" data-task-id="<%= task.id %>"/>	
						<% end %>
						<% if can_manage && task.done == false %>
							<a class="ml-2 text-muted edit_task" href="<%= edit_task_url(task, origin: @origin ? @origin : request.path) %>">
								<span class="oi oi-cog"></span>
							</a>
						<% end -%>
					</small>
		    	</div>
			    <div class="form-check">
			    	<% if can? :close, task %>
			      		<label class="form-check-label">
			        		<input class="form-check-input task_done_checkbox mr-1 mt-2 close_task" data-task-id="<%= task.id %>" onclick="close_task(this)" autocomplete="off" type="checkbox" <% if task.done %> checked="checked" disabled="disabled" <% end %>>
				      		<h6 class="mb-0 pt-1 task_title"><%= task.title %></h6>
				      	</label>
			        <% else -%>
			        	<h6 class="mb-0 pt-1 task_title"><%= task.title %></h6>
			        <% end -%>
			    </div>
		  </li>
		<% end %>
	<% end %>
  </ul>

app/views/tasks/_widget.html.erb
<div class="card">
  <div class="card-header h6">
      <span class="badge badge-default float-right">
        <% if defined? filter %>
          <%= "Für dieses Mandat" unless filter[:mandate_id].blank? %>
          <%= "Für dieses Ressort" unless filter[:department_id].blank? %>
        <% else %>
          Alle Meine
        <% end -%>
      </span>

      Aufgaben
  </div>
  <div class="card-body p-2">
    <form href="#" id="new_task_form" name="new_task_form" style="position: relative;" class="m-0">
          <button type="submit" class="btn btn-secondary btn-sm" style="position: absolute; right:0px;" ><span class="oi oi-action-redo"></span></button>
          <input name="task[title]" id="task_title" type="text" class="form-control " style="border:none; border-bottom: #0275d8 solid 1px; border-radius:0px" placeholder="Neue Aufgabe" autocomplete="off">
          <% if defined? filter %>
            <% filter.each do |key, value|  %>
              <input name="task[<%= key %>]" id="task[<%= key %>]" type="hidden " value="<%= value %>" class="form-control " style="display:none;" autocomplete="off">
            <% end %> 
          <% end %>
    </form>
  </div>
  <div id="tasks_widget_listing"><%= render "tasks/listing", tasks: tasks %></div>
</div>
<p align="right" class="mb-3"><small>
  <% done_url = "/tasks/done" 
    if defined? filter.first
      done_url += "?filter[" + filter.first[0].to_s + "]=" + filter.first[1].to_s
    end 
  %>
  <a href="<%= done_url %>">Erledigte anzeigen</a></small>
</p>
<script type="text/javascript">

  <%-# INFO - Die Filter-Variable aus Rails, bezieht sich auf die Filterung der Tasks die vom Server kommen, nachdem der User Tasks bearbeitet %>
  
  $('#new_task_form').submit(function(e) {
    e.preventDefault();
    var form = {
      <% if defined? filter %>
        "filter":<%= raw(filter.to_json)  %>
      <% end %>
    };
    $.each($(this).serializeArray(), function (i, field) { form[field.name] = field.value || ""; });
    $('#tasks_widget_listing').load('/tasks.htmlp', form, function(){  $('#task_title').val("") });
  });

  var close_task = function (el) {
    if (confirm("Aufgabe erledigt?")) {
      $('#tasks_widget_listing').load('/tasks/' + $(el).data().taskId + '/close.htmlp', {
        <% if defined? filter %>"filter":<%= raw(filter.to_json)  %><% end %>
      });
    } else {
      el.checked = false;
    }
  }

  var set_deadline = function (el) {
    if (el.value.length < 9) return;

    $.ajax('/tasks/' + $(el).data().taskId + '.htmlp', {
      method: "PUT",
      data: {
        task: {"deadline_string": el.value}
        <% if defined? filter %>,"filter":<%= raw(filter.to_json)  %><% end %>
      },
      success: function (data) {
        $('#tasks_widget_listing').html(data);
      }
    });
  }
 
</script>

app/views/tasks/done.html.erb
<h3>Erledigte Aufgaben</h3>

<%= render "listing", tasks: @tasks %>

app/views/tasks/edit.html.erb
<h2>Aufgabe bearbeiten</h2>
<%= render "form", task: @task %>

app/views/tasks/new.html.erb
<h2>Neue Aufgabe</h2>
<%= render "form", task: @task %>