config/routes.rb
Rails.application.routes.draw do

  devise_for :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount ActionCable.server => '/cable'

  resources :projects do
    collection do
      get 'archived'
    end
    member do
      post 'add_member'
      post 'remove_member'
    end
  end
  
  resources :members do
    member do
      post 'lock'
      get 'qualification'
    end
    collection do
      patch 'update_password'
      get 'public'
      get 'departments'
      get 'annotations'
      get 'qualifications'
    end
  end

  resources :annotations
  resources :inquiries
  resources :people

  resources :fee_payments do
    collection do
      get 'reset_all'
      delete 'reset_all'
      post 'email'
    end
  end

  resources :courses do
    member do
      post 'email'
      post 'add_member/:member_id', to: 'courses#add_member', as: :add_member_to
      post 'remove_member/:member_id', to: 'courses#remove_member', as: :remove_member_from
    end
  end

  resources :consultations do
    member do
      post 'email'
    end
  end

  resources :bibliographies do
    resources :documents do
      member do
        get 'get_attachment'
        get 'thumbnail'
      end
    end
  end

  resources :events do
    collection do
      #get 'index'
      get 'export', defaults: { format: 'ics' }
      get 'calendar'
    end
    member do
      post 'add_member/:member_id', to: 'events#add_member', as: :add_member_to
      post 'remove_member/:member_id', to: 'events#remove_member', as: :remove_member_from

      patch 'attend', to: 'events#attend'
      patch 'unattend', to: 'events#unattend'
      post 'email'
    end
  end

  patch 'attendances/:id/permit', to: 'attendances#permit', as: :permit_attendance
  patch 'attendances/:id/unpermit', to: 'attendances#unpermit', as: :unpermit_attendance
  patch 'attendances/:id/award', to: 'attendances#award', as: :award_attendance
  patch 'attendances/:id/unaward', to: 'attendances#unaward', as: :unaward_attendance


  resources :tasks do
    collection do
      get 'done'
    end
    member do
      post 'close'
    end
  end

  get 'public_mandates', to: 'mandates#public_index', as: :public_mandates
  get 'public_people', to: 'people#public_index', as: :public_people
  get 'suggest_person', to: 'people#suggest', as: :suggest_person
  get 'suggest_member', to: 'members#suggest', as: :suggest_member

  get 'rights', to: 'members#index_rights', as: :members_rights
  get 'rights/:id/edit', to: 'members#edit_right', as: :edit_member_right
  patch 'rights/:id', to: 'members#update_right', as: :update_member_right

  resources :conversations do
    resources :messages, only: :create do
      get 'get_attachment'
      get 'thread'
    end
  end

  resources :mandates do
    resources :assignments, only: [:update, :destroy]
    patch 'apply', to: 'assignments#apply'
    patch 'unapply', to: 'assignments#unapply'
    member do
      post 'request_review'
      get 'get_attachment'
      post 'add_member/:member_id', to: 'mandates#add_member'
    end
  end
  get 'window', to: 'window#home', as: :window
  get 'window/detail/:access_code', to: 'window#detail', as: :window_detail
  post 'window/message', to: 'window#message', as: :window_message

  get 'departments/:id', to: 'departments#show', as: :departments # TODO is this still in use?

end

app/models/fee_payment.rb
# original domain model name: Finanzdaten eines Mitgliedes
class FeePayment < ActiveRecord::Base
  belongs_to :member
end

app/controllers/fee_payments_controller.rb
class FeePaymentsController < ApplicationController

  load_and_authorize_resource
  before_action :set_fee_payment, only: [:update,:show]

  def reset_all
    if request.delete?
      for member in Member.all
        member.fee_payment.update(paid:false) if member.fee_payment
      end
      redirect_to fee_payments_path, notice: 'Die Zahlungsdaten aller Mitglieder wurden erfolgreich zurückgesetzt.'
    end
  end

  def email
      Member.with_open_payment do |m|
        ApplicationMailer.delay.info(m.id, params[:email_subject], params[:email_body])
      end
      head :ok, content_type: "text/html"
  end

  def index
    if params[:open] == 'true'
      @open = true
      @members = Member.with_open_payment
    else
      @members = Member.all
    end
  end

  def update
    if @fee_payment.update(fee_payment_params)
      redirect_to fee_payments_path, notice: 'Finanzdaten wurden erfolgreich aktualisiert.'
    end
  end

  def show
  end

  private

  def set_fee_payment
    @fee_payment = FeePayment.find(params[:id])
  end

  def fee_payment_params
    params.require(:fee_payment).permit(:account_details,:payment_history_notes,:paid,:direct_debit_allowed)
  end
end

app/views/fee_payments/_row.html.erb
<div class="row">
  <div class="col-6">
    <table>
      <% unless fee_payment.blank? %>
            <tr><td class="small text-right pr-2"><b>Lastschrifterlaubnis</b></td><td><%= fee_payment.direct_debit_allowed ? 'Erteilt' : 'Nicht erteilt' %></td></tr>
            <tr><td class="small text-right pr-2"><b>Kontoverbindung</b></td><td><%= fee_payment.account_details %></td></tr>
      <% end %>
      <%= render(:partial => 'members/login_data', :formats => [:html], locals: {member: fee_payment.member}) %>
    </table>
  </div>

  <div class="col-4">
    <% unless fee_payment.blank? %>
        <span class="small text-right pr-2"><b>Notizen zur Bezahlhistorie</b><br>
        <% if fee_payment.payment_history_notes && fee_payment.payment_history_notes != '' %>
              <%= fee_payment.payment_history_notes %>
              <% else %>
                Bisher keine Notizen
              <% end %>
        <br><br>
    <% end %>
  </div>

  <div class="col-2">
      <%= link_to( fee_payment_path(fee_payment) , {class: "btn btn-primary btn-sm float-right attend_button"}  ) do %>Bearbeiten<% end %>
  </div>
</div>

app/views/fee_payments/index.html.erb
<div class="float-right"><%= link_to( reset_all_fee_payments_path , {class: ""}  ) do %>Weitere Aktionen<% end %></div>

<h2>Zahlungsübersicht</h2>
<div class="row mb-3">
  <div class="col-4">
    <% if not @open %>
      <span class="oi oi-check text-success"></span> - Bezahlt
    <% end %>
    <div class="pb-2 "><span class="oi oi-x text-danger"></span>  - Noch nicht bezahlt</div>
    <% if not @open %>
      <%= link_to "Nur offene Zahlungen anzeigen", fee_payments_path(params:{open:true}), class: "btn btn-sm btn-secondary"   %>
    <% else %>
      
        <%= link_to "Alle anzeigen", fee_payments_path, class: "btn btn-sm btn-secondary mb-2" %>

        <button class="btn btn-sm btn-secondary" onclick="$('#open_payments_email_form').show(); $(this).hide()">Email an Mitglieder mit offener Zahlung</button>
      
    <% end %>
  </div>
  <div class="col-8">
    <div id="open_payments_email_form" class="card " style="display:none">
      <div class="card-header">
        Zahlungserinnerung
      </div>
      <div class="card-body">
        <%= render "emails/form", action: email_fee_payments_path() %>
      </div> 
    </div>
  </div>
</div>


  
  




<% if !@members.blank? %>
    <div id="accordion" role="tablist" class="accordion" aria-multiselectable="false">
      <% for member in @members %>
          <div class="card">
            <div class="card-header" role="tab" id="member-<%= member.id %>">
              <a data-toggle="collapse" data-parent="#accordion" href="#member-<%= member.id %>-content" aria-expanded="true" aria-controls="member-<%= member.id %>-content">
                <div class="d-flex flex-row justify-content-start">
                  <div class="p-2 h6 m-0 col-4 member_full_name"><%= member.full_name %></div>

                  <div class="p-2 small col-4 departments-list"><%= member.departments.map { |n| DEPARTMENT_TITLES[n] }.join(", ") %></div>

                  <div class="p-2 col-4"><span class="float-right oi oi-<%= member.fee_payment && member.fee_payment.paid ? "check text-success" : "x text-danger" %>"></span></div>
                </div>
              </a>
            </div>

            <% if member.fee_payment %>
              <div data-id="<%= member.fee_payment.id %>"  id="member-<%= member.id %>-content" class="collapse" role="tabpanel" aria-labelledby="member-<%= member.id %>">
                <div class="card-body">
                  <%= render 'row', fee_payment: member.fee_payment %>
                </div>
              </div>
            <% end %>
          </div>
      <% end %>
    </div>
<% end %>

app/views/fee_payments/reset_all.html.erb
<div class="col-md-6">
<%= render 'common/back', text: ' Zurück zur Übersicht', path: fee_payments_path %>
<br>
<br>
<br>

  <h2>Zahlungsdaten zurücksetzen</h2>
  <p>
    Hier kannst du sämtliche Zahlungsdaten zurücksetzen.
    Alle Mitglieder erhalten dann wieder den Zahlungsstatus 'nicht bezahlt'.
    Beachte, dass die Aktion nicht mehr rückgängig gemacht werden kann.
  </p>

  <br>

  <%= button_to "Sämtliche Zahlungsdaten jetzt zurücksetzen",
                { :action => "reset_all", }, class: 'btn btn-primary',
                method: :delete, data: {confirm: "Sicher?"} %>
</div>

app/views/fee_payments/show.html.erb
<%= render 'common/back', text: ' Zurück zur Übersicht', path: fee_payments_path %>
<div class="my-3">
  <%= render 'members/core_data', member: @fee_payment.member %>
</div>
<%= form_for @fee_payment do |f| %>

    <div class="row mb-3">
      <div class="col-6"><h4>Finanzdaten</h4></div>
      <div class="col-6" align="right">
        <%= f.submit "Finanzdaten speichern", class: "btn btn-primary" %>
      </div>
    </div>

    <div class="row">
      <div class="col-6">
        <div class="form-group">
          <label>Kontoverbindung(en)</label>
          <%= f.text_area :account_details, class:"form-control" %>
        </div>
        <div class="form-group">
          <label>Notizen zu Bezahlhistorie</label>
          <%= f.text_area :payment_history_notes, class:"form-control" %>
        </div>
      </div>
      <div class="col-6">
        
        <div class="form-group">
          
            <label>Bezahlstatus</label><br>
            <%= f.check_box :paid %>
            <%= f.label :paid, "bezahlt" %>
            </div>
        <div class="form-group">

            <label>Erlaubnis zum Einzug per Lastschrift</label><br>
            <%= f.check_box :direct_debit_allowed %>
            <%= f.label :direct_debit_allowed, "erteilt" %>
       </div>
      </div>
    </div>
<% end %>