config/routes.rb
Rails.application.routes.draw do

  devise_for :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount ActionCable.server => '/cable'

  resources :projects do
    collection do
      get 'archived'
    end
    member do
      post 'add_member'
      post 'remove_member'
    end
  end
  
  resources :members do
    member do
      post 'lock'
      get 'qualification'
    end
    collection do
      patch 'update_password'
      get 'public'
      get 'departments'
      get 'annotations'
      get 'qualifications'
    end
  end

  resources :annotations
  resources :inquiries
  resources :people

  resources :fee_payments do
    collection do
      get 'reset_all'
      delete 'reset_all'
      post 'email'
    end
  end

  resources :courses do
    member do
      post 'email'
      post 'add_member/:member_id', to: 'courses#add_member', as: :add_member_to
      post 'remove_member/:member_id', to: 'courses#remove_member', as: :remove_member_from
    end
  end

  resources :consultations do
    member do
      post 'email'
    end
  end

  resources :bibliographies do
    resources :documents do
      member do
        get 'get_attachment'
        get 'thumbnail'
      end
    end
  end

  resources :events do
    collection do
      #get 'index'
      get 'export', defaults: { format: 'ics' }
      get 'calendar'
    end
    member do
      post 'add_member/:member_id', to: 'events#add_member', as: :add_member_to
      post 'remove_member/:member_id', to: 'events#remove_member', as: :remove_member_from

      patch 'attend', to: 'events#attend'
      patch 'unattend', to: 'events#unattend'
      post 'email'
    end
  end

  patch 'attendances/:id/permit', to: 'attendances#permit', as: :permit_attendance
  patch 'attendances/:id/unpermit', to: 'attendances#unpermit', as: :unpermit_attendance
  patch 'attendances/:id/award', to: 'attendances#award', as: :award_attendance
  patch 'attendances/:id/unaward', to: 'attendances#unaward', as: :unaward_attendance


  resources :tasks do
    collection do
      get 'done'
    end
    member do
      post 'close'
    end
  end

  get 'public_mandates', to: 'mandates#public_index', as: :public_mandates
  get 'public_people', to: 'people#public_index', as: :public_people
  get 'suggest_person', to: 'people#suggest', as: :suggest_person
  get 'suggest_member', to: 'members#suggest', as: :suggest_member

  get 'rights', to: 'members#index_rights', as: :members_rights
  get 'rights/:id/edit', to: 'members#edit_right', as: :edit_member_right
  patch 'rights/:id', to: 'members#update_right', as: :update_member_right

  resources :conversations do
    resources :messages, only: :create do
      get 'get_attachment'
      get 'thread'
    end
  end

  resources :mandates do
    resources :assignments, only: [:update, :destroy]
    patch 'apply', to: 'assignments#apply'
    patch 'unapply', to: 'assignments#unapply'
    member do
      post 'request_review'
      get 'get_attachment'
      post 'add_member/:member_id', to: 'mandates#add_member'
    end
  end
  get 'window', to: 'window#home', as: :window
  get 'window/detail/:access_code', to: 'window#detail', as: :window_detail
  post 'window/message', to: 'window#message', as: :window_message

  get 'departments/:id', to: 'departments#show', as: :departments # TODO is this still in use?

end

app/models/document.rb
class Document < ActiveRecord::Base
	belongs_to :member
	belongs_to :bibliography
	has_attached_file :attachment,
                    	path: ':rails_root/user_files/:class/:id/:style/:basename.:extension',
                    	styles: lambda { |a|  if a.content_type =~ %r(image|pdf) then return { :thumb => ["300x300>", :png] } else return {} end  } 
    validates_attachment_content_type :attachment, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.oasis.opendocument.text", "application/vnd.oasis.opendocument.spreadsheet"]
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  load_and_authorize_resource 

  before_action :set_document, only: [:update, :edit, :show, :get_attachment, :destroy]

  def new
    @bibliography = Bibliography.find(params[:bibliography_id])
  	@document = Document.new
  end

  def edit
  end

  def create
    @bibliography = Bibliography.find(params[:bibliography_id])

  	@document = @bibliography.documents.new(document_params.merge({member_id: current_member.id}))
    if @document.save
      redirect_to bibliography_path(@bibliography), notice: 'Dokument wurde erfolgreich hinzugefügt.'
    else
      render action: 'new'
    end
  end

  def update
    if @document.update(document_params)
      redirect_back(
          notice: 'Dokument wurde erfolgreich aktualisiert.',
          fallback_location: root_path
      )
    end
  end

  def get_attachment
		head(:not_found) and return if @document.nil? or not @document.attachment.exists?
		head(:bad_request) and return unless File.exist?(@document.attachment.path)
		  
		send_file_options = { filename: @document.attachment_file_name, type: @document.attachment_content_type }
		send_file(@document.attachment.path, send_file_options)
	end

  def thumbnail
    head(:not_found) and return if @document.nil? or not @document.attachment.exists?
    head(:bad_request) and return unless File.exist?(@document.attachment.path(:thumb))
      
    send_file_options = { filename: @document.attachment_file_name, type: "png" }
    send_file(@document.attachment.path(:thumb), send_file_options)
  end


  def destroy
    @bibliography = @document.bibliography
    if @document.destroy
      redirect_to bibliography_path(@bibliography), notice: 'Dokument wurde erfolgreich gelöscht.'
    end
  end


  private

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:title,:tags,:comment,:attachment)
  end
end

app/views/documents/_document.html.erb
<div class="list-group-item  list-group-item-action flex-column align-items-start">
	<div class="d-flex w-100 justify-content-between">
		<div>
			<h5 class="mb-0 document-title"><%= document.title %></h5>
			<%= document.comment %>
			<br>

			<span class="small text-muted font-italic" >
				Schlagwörter: <%= document.tags %><br>
				Hochgeladen: <%= l document.created_at.localtime, format: :long %>
			</span>
		</div>
		<% if document.attachment.content_type =~ %r(image|pdf) %>
			<%= image_tag thumbnail_bibliography_document_path(@bibliography, document), style: "float:right; width: 100px;" %>
		<% else	%>
			<h6 class="text-muted">.<%= document.attachment_file_name %></h6>
		<% end -%>
	</div>

	


	<div class="d-flex w-100 mt-1 justify-content-between mt-2">
		<%= link_to("Bearbeiten",  edit_bibliography_document_path(@bibliography, document), class:"btn btn-sm btn-secondary") %>
		<a href="<%= get_attachment_bibliography_document_path(@bibliography, document) %>" class="btn btn-sm btn-primary">Download</a>

	</div>
</div>

app/views/documents/_form.html.erb
<%= form_for [@bibliography, @document],  :url =>  (bibliography_document_path unless @document.new_record?)   do |f| %>

  <%= render "common/validation_msg_box", resource: document %>

  <div class="row">
    <div class="col-md-6">

      <div class="form-group">
        <%= f.label "Titel" %>
      	<%= f.text_field :title, class: "form-control" %></div>
        
      <div class="form-group">
        <%= f.label "Schlagwörter" %>
        <%= f.text_field :tags, class: "form-control" %></div>

      <div class="form-group">
        <%= f.label "Kommentar" %>
        <%= f.text_area :comment, class: "form-control", rows: "7" %></div>
      
      <div class="form-group">
        <%= f.label "Datei" %>
        <%= f.file_field :attachment, class: "form-control" %></div>
 
      <%= f.submit "Speichern", class: "btn btn-primary" %>
      
    </div>
    <div class="col-md-6" align="right">
      <%= link_to "Dokument löschen", bibliography_document_path(@document.bibliography_id, @document), method: "DELETE", data: {confirm: "Löschen bestätigen"}, class: "btn btn-sm btn-danger" if can? :destroy, Document and !@document.new_record?  %>

    </div>
  </div>
<% end %>

app/views/documents/edit.html.erb
<%= render 'common/back', text: ' Ordner', path: bibliography_path(@document.bibliography) %>

<h3>Dokument bearbeiten</h3>
<%= render "form", document: @document %>

app/views/documents/new.html.erb
<h3>Neues Dokument</h3>
<%= render "form", document: @document %>