config/routes.rb
Rails.application.routes.draw do

  devise_for :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount ActionCable.server => '/cable'

  resources :projects do
    collection do
      get 'archived'
    end
    member do
      post 'add_member'
      post 'remove_member'
    end
  end
  
  resources :members do
    member do
      post 'lock'
      get 'qualification'
    end
    collection do
      patch 'update_password'
      get 'public'
      get 'departments'
      get 'annotations'
      get 'qualifications'
    end
  end

  resources :annotations
  resources :inquiries
  resources :people

  resources :fee_payments do
    collection do
      get 'reset_all'
      delete 'reset_all'
      post 'email'
    end
  end

  resources :courses do
    member do
      post 'email'
      post 'add_member/:member_id', to: 'courses#add_member', as: :add_member_to
      post 'remove_member/:member_id', to: 'courses#remove_member', as: :remove_member_from
    end
  end

  resources :consultations do
    member do
      post 'email'
    end
  end

  resources :bibliographies do
    resources :documents do
      member do
        get 'get_attachment'
        get 'thumbnail'
      end
    end
  end

  resources :events do
    collection do
      #get 'index'
      get 'export', defaults: { format: 'ics' }
      get 'calendar'
    end
    member do
      post 'add_member/:member_id', to: 'events#add_member', as: :add_member_to
      post 'remove_member/:member_id', to: 'events#remove_member', as: :remove_member_from

      patch 'attend', to: 'events#attend'
      patch 'unattend', to: 'events#unattend'
      post 'email'
    end
  end

  patch 'attendances/:id/permit', to: 'attendances#permit', as: :permit_attendance
  patch 'attendances/:id/unpermit', to: 'attendances#unpermit', as: :unpermit_attendance
  patch 'attendances/:id/award', to: 'attendances#award', as: :award_attendance
  patch 'attendances/:id/unaward', to: 'attendances#unaward', as: :unaward_attendance


  resources :tasks do
    collection do
      get 'done'
    end
    member do
      post 'close'
    end
  end

  get 'public_mandates', to: 'mandates#public_index', as: :public_mandates
  get 'public_people', to: 'people#public_index', as: :public_people
  get 'suggest_person', to: 'people#suggest', as: :suggest_person
  get 'suggest_member', to: 'members#suggest', as: :suggest_member

  get 'rights', to: 'members#index_rights', as: :members_rights
  get 'rights/:id/edit', to: 'members#edit_right', as: :edit_member_right
  patch 'rights/:id', to: 'members#update_right', as: :update_member_right

  resources :conversations do
    resources :messages, only: :create do
      get 'get_attachment'
      get 'thread'
    end
  end

  resources :mandates do
    resources :assignments, only: [:update, :destroy]
    patch 'apply', to: 'assignments#apply'
    patch 'unapply', to: 'assignments#unapply'
    member do
      post 'request_review'
      get 'get_attachment'
      post 'add_member/:member_id', to: 'mandates#add_member'
    end
  end
  get 'window', to: 'window#home', as: :window
  get 'window/detail/:access_code', to: 'window#detail', as: :window_detail
  post 'window/message', to: 'window#message', as: :window_message

  get 'departments/:id', to: 'departments#show', as: :departments # TODO is this still in use?

end

app/models/mandate.rb
class Mandate < ActiveRecord::Base
	has_many :assignments, dependent: :destroy
	has_many :members, through: :assignments
  has_many :tasks
  has_one :conversation

  validates :title, presence: true, allow_blank: false

  belongs_to :client, class_name: "Person", foreign_key: 'client_id', optional: true
  accepts_nested_attributes_for :client

  has_attached_file :attachment,
                      url: '/:class/:id/attachment',
                      path: ':rails_root/user_files/:class/:id/:attachment'
  validates_attachment_content_type :attachment, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.oasis.opendocument.text", "application/vnd.oasis.opendocument.spreadsheet"]

  after_create :create_protocol

	default_scope { order(updated_at: :desc) }

  def create_protocol
    unless self.conversation
      self.conversation = Conversation.create()
    end
  end

  def eql?(other_obj)
    id == other_obj.id
  end

  def hash
    id.to_i
  end

  def vacant
    status == "vacant"
  end

  def done
    status == "done"
  end
  def active
    status == "active"
  end

  def is_assigned_to member_or_member_id
    member_or_member_id = member_or_member_id.id if member_or_member_id.class == Member
    assignments.approved.pluck(:member_id).include? member_or_member_id
  end

  scope :done, -> { where("status = 'done'") }
  scope :undone, -> { where("status != 'done'") }
  scope :active, -> { where("status = 'active'") }

  scope :unapproved, -> { where("assignments.approved != ?", true)}
  scope :approved, -> { where("assignments.approved = ?", true)}

  scope :vacant, -> { where("status = 'vacant'") }

  def application_exists_from(current_member)
    assignments.unapproved.pluck(:member_id).include? current_member.id
  end

end

app/controllers/mandates_controller.rb
class MandatesController < ApplicationController

  include PeopleHelper

  load_and_authorize_resource
	before_action :set_mandate, only: [:edit, :update, :request_review]

  def add_member
    member = Member.find params[:member_id]
    if member == nil or @mandate.is_assigned_to member
      return redirect_to mandates_path, notice: 'Fehler. Das Mitglied ist entweder unbekannt oder bereits als Bearbeiter hinzugefügt.'
    end

    unless as = Assignment.find_by(member_id: member.id, mandate_id: @mandate.id) 
      as = @mandate.assignments.create(member_id: member.id)
    end
    as.update(approved:true)

    redirect_to mandates_path({open: @mandate.id}), notice: "#{member.full_name} wurde erfolgreich als Bearbeiter hinzugefügt."
  end

  def edit
  end
  def show
    ConversationView.create_or_update_for @mandate.conversation.id, current_member.id
  end

  def new
  	@mandate = Mandate.new
    @department_id = params[:department_id]
  end

  def public_index
    @vacant_mandates = Mandate.vacant
  end

  def index
    if params['supervision'] and params['supervision'] == 'true'
      @mandates = Mandate.undone.order('updated_at DESC').where('supervised = ?',false)
      @supervision = true
    elsif params['from']
      @from = params['from'].to_i
      @count = Mandate.done.count
      @mandates = Mandate.done.order('updated_at DESC').offset(params['from']).limit(Rails.configuration.x.page_items)
    else
  	  @mandates = Mandate.undone
    end
  end

  def get_attachment
      head(:not_found) and return if (@mandate = Mandate.find(params[:id])).nil? or not @mandate.attachment.exists?
      head(:bad_request) and return unless File.exist?(@mandate.attachment.path)
        
      send_file_options = { filename: @mandate.attachment_file_name, :type => @mandate.attachment_content_type }
      send_file(@mandate.attachment.path, send_file_options)
  end

  def request_review
    return redirect_to mandate_path(@mandate),
       notice: 'Erforderliche Qualifikationen nicht vorhanden.' unless current_member.full_qualified

    @mandate.status = "awaits_review"
    if @mandate.save
      redirect_back(
          notice: 'Die Anfrage zur Abnahme des Mandats wurde gespeichert.',
          fallback_location: root_url
      )
    end
  end

  def create
    @mandate.code = SecureRandom.urlsafe_base64 8

    if @mandate.save
      notice = 'Mandat wurde erfolgreich hinzugefügt.'
      return redirect_to root_path, notice: notice if params[:department_id].to_i == SPRECHSTUNDE
      redirect_to mandates_path, notice: notice
    else
      render action: 'new'
    end
  end

  def update
    if not can? :manage, Mandate and trying_to_change_client
      return redirect_back(
          notice: 'Fehler: Nur Mitglieder der Mandatsverwaltung können die Mandatenzuordnung ändern.',
          fallback_location: root_url
      )
    end

  	if @mandate.update(mandate_params)
      redirect_to edit_mandate_path, notice: 'Mandat wurde erfolgreich aktualisiert.'
    else
      render action: 'edit'
    end
  end

  private

    def trying_to_change_client
      params['mandate']['client_id'] and @mandate.client_id != params['mandate']['client_id'].to_i
    end

    def set_mandate
      @mandate = Mandate.find(params[:id])
    end

    def mandate_params
      set_client_attrs(params.require(:mandate).permit(
          :title, :description, :supervised, :status, :client_id, :attachment, :code, client_attributes: permitted_client_attrs
      ))
    end
end

app/views/mandates/_code.html.erb
<div class="card mb-3">
  <div class="card-header h6">
    <span data-toggle="tooltip" title="Das Mandatsfenster erlaubt den Mandaten, den Status des Mandates einzusehen, und Nachrichten inkl. Anhängen hochzuladen. Für den anonymen Zugang sind die hier aufgeführten Codes notwendig. Bitte teile diese Codes der jeweiligen Mandantin / dem jeweiligen Mandanten mit.">Mandantenfenster</span>
  </div>
  <div class="card-body">
    <% if @mandate.code %>
        <table>
          <tr><td data-toggle="tooltip" title="Der Zugangscode erlaubt, im Mandantenfenster auf die Ansicht des Mandates zu gelangen. Der Bestätigungscode wird für das Abschicken einer Nachricht aus der Mandatsansicht des Mandantenfenster heraus benötigt.">Zugangscode:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="access_code"><%= @mandate.code[0,6] %></span></td></tr>
          <tr><td>Bestätigungscode:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="confirmation_code"><%= @mandate.code[6,10] %></span></td></tr>
        </table>
    <% end %>
  </div>
</div>

app/views/mandates/_form.html.erb
<%= form_for mandate, {name: "mandate_form"} do |f| %>

<%= render "common/validation_msg_box", resource: mandate %>

<div class="row">

  <div class="col-md-6 mb-3">

    <div class="form-group">
      <%= f.label :titel %>
      <%= f.text_field :title, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, t('mandate.description') %>
      <%= f.text_area :description, class:"form-control", rows:"10" %>
    </div>

    <div class="form-group">
      <%= f.label :attachment, "Dokument" %>

      <% if @mandate.attachment.exists? %>
        <p>
          <small>
            Aktuelles Dokument: 
            <%= link_to @mandate.attachment_file_name, get_attachment_mandate_path(@mandate), target: "_blank" %>
            <br>Durch Auswählen einer anderen Datei wird das aktuelle Dokument überschrieben
          </small>
        </p>
      <% end -%>
      <%= f.file_field :attachment, class: "form-control" %>
    </div>

    <div class="card mt-4">
      <div class="card-header h6">
          Bearbeiter
      </div>
      <div class="card-body p-3">
        <table class="table table-sm">
          <% assignments = mandate.assignments.order(:approved) %>
          <% if assignments.any? %>
            <%= render assignments, done: mandate.done, admin_mode: false %>
          <% else %>
            <tr><td  colspan="4"><small>Noch keine Bewerbungen oder Zuweisungen für dieses Mandat</small></td></tr>
          <% end %>
        </table>
      </div>
    </div>

  </div>
  <div class="mb-3 col-md-6">



    <div class="card mb-3">
      <div class="card-header h6">
        Status
      </div>
      <div class="card-body">
        <% if can? :manage, Mandate %>
          <div class="custom-controls-stacked">
            <div class="form-check">
              <%= f.radio_button :status, 'vacant', class:"form-check-input" %>
              <label class="form-check-label" for="status" data-toggle="tooltip" title="Ist ein Mandat vakant, so wird es in der Mandatsbörse angezeigt und Mitglieder können sich bewerben, an dessen Bearbeitung teilzunehmen. Die Mandatsverwaltung kann dann die Bewerber sehen und zulassen. Wird das Mandat auf 'aktiv' geschaltet, so sind keine Bewerbungen mehr möglich und es können keine Zuweisungen mehr vorgenommen werden.">Vakant</label>
            </div>
            <div class="form-check">
              <%= f.radio_button :status, 'active', class:"form-check-input" %>
              <label class="form-check-label" for="status" data-toggle="tooltip" title="Aktive Mandate sind in Bearbeitung und werden nicht mehr in der Mandatsbörse angezeigt. Sind Mandate aktiv, so können dem Mandat zugewiesene, voll qualifizierte Mitglieder zum Ende der Bearbeitung die Abnahme des Mandates anfragen.">Aktiv</label>
            </div>
            <div class="form-check">
              <%= f.radio_button :status, 'awaits_review', class:"form-check-input" %>
              <label class="form-check-label" for="status" data-toggle="tooltip" title="Sobald ein voll qualifiziertes, dem Mandat zur Bearbeitung zugewiesenes Mitglied die Abnahme anfragt, wird das Mandat in der Übersicht mit einem orangenem Fähnchen ausgezeichnet. Nach einer Revision des Mandates durch die Mandatsverwaltung kann das Mandat, wenn alles in Ordnung ist, anschließend geschlossen werden (Status 'erledigt').">Wartet auf Abnahme</label>
            </div>
            <div class="form-check">
              <%= f.radio_button :status, 'done', class:"form-check-input" %>
              <label class="form-check-label" for="status" data-toggle="tooltip" title="Erledigte Mandate werden archiviert und sind erreichbar über den Button 'Bereits erledigte anzeigen'. Sollen nachträglich Änderungen an archivierten Mandaten vorgenommen vorgenommen werden, so müssen diese zuerst wieder in den Status aktiv gesetzt werden.">Erledigt</label>
            </div>
          </div>
        <% else %>
          <h5><%= t "mandate.status.#{@mandate.status}" %></h5>
          <% if @mandate.status == "active" and can? :request_review, Mandate and not can? :manage, Mandate %>
              <a href="<%= request_review_mandate_path %>" confirm="Abnahme starten?" data-method="post">Abnahme anfragen</a>
          <% end %>
        <% end %>
      </div>
    </div>

    <% if can? :manage, Mandate %>
      <div class="card mb-3">
        <div class="card-header h6">
          Supervision
        </div>
        <div class="card-body">
          
          <div class="form-check">
            
            <%= f.check_box :supervised, class:"form-check-input" %>
            <label class="form-check-label" for="supervised">
              durchgeführt
            </label>
          </div>
        </div>
      </div>
    <% end %>

    <%= render 'code' %>

    <%= render "people/client_select_card", parent_form: f, owner: mandate %>

    <%= hidden_field_tag(:department_id, @department_id) %>
    <% if @department_id %>
      <input type="submit" name="commit" value="Speichern" class="mt-3 btn btn-primary"
             data-disable-with="Speichern" data-toggle="tooltip" data-placement="top"
             title="Beachte, dass das Mandat später nur noch durch die Mandatsverwaltung editiert werden kann.">
      <span></span>
    <% else %>
      <%= f.submit "Speichern",  class: "mt-3 btn btn-primary" %>
    <% end %>
  </div>  
</div>
<% end %>

app/views/mandates/_heading.html.erb
<div class="float-right">
  <% if mandate.assignments.approved.count > 0 and not mandate.done %>
      <div class="badge badge-default approved-notice">
        <%= mandate.assignments.approved.count %>&nbsp<%= t('mandate.notice.approved', count: mandate.assignments.approved.count)%></div>
  <% elsif not mandate.vacant and not mandate.done %>
      <div class="badge badge-danger lacking-approved-member-notice">Warnung: Mandat aktiv, jedoch ohne Zuweisung</div>
  <% end %>

  <% if mandate.vacant %>
      <% if mandate.assignments.unapproved.count > 0 %>
          <div class="badge badge-success application-notice">
            <%= mandate.assignments.unapproved.count %> Bewerber</div>
      <% else %>
          <div class="badge badge-calm">Keine Bewerbungen</div>
      <% end %>
  <% end %>
  <span class="oi oi-eye ml-2 <% unless mandate.supervised %> text-calm <% end %>"></span>
</div>

<div class="h6 mb-0" >
  <%= render "common/mandate_icon", mandate: mandate %>
  <%= mandate.title %>
</div>

app/views/mandates/_listing.html.erb
<% if !mandates.blank? %>
  <div class="mandates_listing">
    <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
    		<% for mandate in mandates %>
    			<div class="card" style="overflow: visible;">
					  <div class="card-header" data-parent="#accordion" data-target="#mandate-<%= mandate.id %>" data-toggle="collapse" style="background-color: white" role="tab" id="mandate-<%= mandate.id %>-heading">
					    <%= render 'mandates/heading', mandate: mandate %>

					  </div>

					  <div data-url="<%= mandate_url(mandate) %>.htmlp"  id="mandate-<%= mandate.id %>" class="collapse bg-light" role="tabpanel" aria-labelledby="mandate-<%= mandate.id %>-heading">
					    <div class="card-body">
					   	 Lade...
					    </div>
					  </div>
					</div>
    		<% end %>
    		
    </div>
  </div>
<% else %>
	<div>
    Keine
  </div>
<% end %>

<script type="text/javascript">
    $('#accordion').on('shown.bs.collapse', function (e) {
        var t = $(e.target.children[0]);
        if (t.text().length < 50) t.load($(e.target).data('url'));
    });

    <% if params["open"] %>
    	$('#mandate-<%= params["open"] %>').collapse('show').get(0).scrollIntoView(true);
    <% end %>
</script>

app/views/mandates/_mandate.html.erb
<div class="row">
  <div class="col-md-4">
    <p>
      <small class="bold">Mandant*in</small><br>
      <%= if mandate.client then mandate.client.name else "Niemand" end %>
    </p>

    <p>
      <small class="bold">Beschreibung</small><br>
      <%= mandate.description %>
    </p>
  </div>

  <div class="col-md-4">
    <p>
      <small class="bold">Zuletzt geändert</small><br>
      <%= l mandate.updated_at.localtime, format: :long %>
    </p>

    <p>
      <small class="bold">Erstellt</small><br>
      <%= l mandate.created_at.localtime, format: :long %>
    </p>

    <p>
      <% if message = mandate.conversation.messages.last %>
        <% if member = mandate.conversation.messages.last.member %>
          
              <small class="bold">Letzter Protokolleintrag</small><br>
              <i><%= member.first_name %>, <%= l mandate.conversation.messages.last.created_at, format: :long %></i>: <%= mandate.conversation.messages.last.text %>
            
        <% end -%>
      <% end -%>

    </p>
  </div>

  <div class="col-md-4" align="right">
    <%= link_to "Protokoll", mandate_path(mandate), class: "btn btn-sm mb-2 btn-secondary" if can? :show, mandate %>
    <%= render "common/pencil", path: edit_mandate_path(mandate) %>
  </div>
</div>


<div id='<%= "extra_card_content_#{mandate.id}" %>' %>
  <table class="table table-sm">
    <tr><th class="border-0 h6" colspan="4">Bearbeiter</th></tr>
    <% assignments = mandate.assignments.order(:approved) %>
    <% if assignments.any? %>
      <%= render assignments, done: mandate.done, admin_mode: true %>
    <% else %>
      <tr><td  colspan="4"><small>Noch keine Bewerbungen oder Zuweisungen für dieses Mandat</small></td></tr>
    <% end %>

  </table>
</div>

<div class="input-group">
  <input type="text" class="form-control" placeholder="Bearbeiter hinzufügen..." id="course_<%= mandate.id %>_member_suggest" autocomplete="off">
  <span class="input-group-btn"><button type="button"  class="btn btn-warning" onclick="mandate_<%= mandate.id %>_select_member()"><span class="oi oi-collapse-up"></span></button></span>
</div>

<script>
    $('#course_<%= mandate.id %>_member_suggest').typeahead({
        source: function (query, process) {
            $.get('/suggest_member.json?query='+query, function(data) {
                process(data);
            });
        }
    });

    function mandate_<%= mandate.id %>_select_member() {
        var memberId= ($('#course_<%= mandate.id %>_member_suggest').typeahead("getActive")).id;
        var memberName= ($('#course_<%= mandate.id %>_member_suggest').typeahead("getActive")).name;

        $.post( "/mandates/<%= mandate.id %>/add_member/"+memberId, function(data) {
            if (data.status == 'ok') {
                location.reload();
            }
        });
    }
</script>

app/views/mandates/edit.html.erb
<%= render 'common/back', text: ' Zurück zur Übersicht', path: mandates_path %>
<br>
<br>

<h2><%= @mandate.title %></h2>

<%= render "form", mandate: @mandate %>

app/views/mandates/index.html.erb
<div class="row">
  <div class="col-md-9">
    <h2><%= (t 'domain_model.mandates') + ' verwalten' %></h2>
  </div>
  <div class="col-md-3" align="right">
    <%= render "common/plus", path: new_mandate_path %>
  </div>
</div>

  <div align="center">

  <% if not @from and not @supervision %>
    <span data-toggle="tooltip" data-placement="bottom" title="Zeigt alle Mandate an, die noch keine Supervision erfahren haben, und die weiterhin entweder aktiv sind oder auf Abnahme warten und noch nicht archiviert sind." >
      <%= link_to "Supervisionsfilter", mandates_url+"?supervision=true", class: "btn btn-secondary btn-sm" %>
    </span>
  <% end %>

  <% if not @from and not @supervision %>
      <%= render 'common/show_archived', path: mandates_url %>
  <% end %>
</div>


<% if @from or @supervision%>
    <%= render 'common/show_open', path: mandates_url %>
    &nbsp;
  <%= render "listing", mandates: @mandates, show_pencil: true, show_assignments: true, show_icons: false, show_assignment_actions: false %>
<% else %>
    &nbsp;
  <%= render "listing", mandates: @mandates, show_pencil: true, show_assignments: true, show_icons: true, show_assignment_actions: true %>
<% end %>

&nbsp;



<%= render 'common/load_more', path: mandates_url, from: @from, count: @count %>

app/views/mandates/new.html.erb
<h2>Neues Mandat erstellen</h2>



<div class="row">
  <div class="col s12">
    <h2><%= @mandate.title %></h2>
    <%= render "form", mandate: @mandate %>
  </div>
</div>

app/views/mandates/public_index.html.erb
<h2>Mandatsbörse</h2>

Dein aktueller Status:&nbsp;
  <%= QUALIFICATION_LEVELS[current_member.qualification_level] %><br>


<div id="mandate_market_your_mandates" class="mt-4">
  <h5>Deine Mandate</h5>
  <%= render "mandates/market/listing", id_attribute: "your_mandates_approved_undone", mandates: current_member.mandates.approved.undone + current_member.mandates.unapproved.undone %>
</div>


<div id="mandate_market_open" class="mt-4">
  <h5><% if not (current_member.assignments.unapproved.blank? and current_member.mandates.approved.undone.blank? )  %>Weitere Mandate<% end %></h5>
  <% if not @vacant_mandates.blank? %>
      <%= render "mandates/market/listing", id_attribute: "mandates_unapproved", mandates: @vacant_mandates - current_member.mandates.unapproved - current_member.mandates.approved  %>
  <% else %>
      <br>Keine offenen Mandate vorhanden
  <% end %>
</div>

app/views/mandates/show.html.erb
<h2><%= @mandate.title %></h2>

<div class="row">
  <div class="col-md-7">

    <%= render "conversations/protocol", conversation: @mandate.conversation if @mandate.conversation %>
  </div>

  <div class="col-md-5">
  	<div class="card mb-3">
    	<div class="card-header h6">
    	 Status
    	</div>
    	<div class="card-body pb-1">
    		<h5><%= t "mandate.status.#{@mandate.status}" %></h5>

        <% if @mandate.status == "active" and can? :request_review, @mandate %>
            <p class="request_review_action" align="right"><a href="<%= request_review_mandate_path %>" confirm="Abnahme starten?" data-method="post">Abnahme anfragen</a></p>
        <% end %>

    	  <br>
        <small style="color:gray"><b>BEARBEITER</b></small>
      </div>

      <ul class="list-group list-group-flush">
        <% for ass in @mandate.assignments.approved %>
            <li class="list-group-item">
              <span><%= ass.member.full_name %></span>
              <%= render "assignments/qualification_level_badge", member: ass.member %>
            </li>
          <% end %>
      </ul>
    </div>
    <% unless @mandate.new_record? %>
        <%= render "tasks/widget", tasks: @mandate.tasks.undone, filter: { mandate_id: @mandate.id } %>
    <% end %>

    <div class="card mb-3">
      <div class="card-header h6">
        Beschreibung
      </div>
      <div class="card-body">
        <%= simple_format @mandate.description %>
      </div>
      <% if @mandate.attachment.exists? %>
        <div class="card-footer">
          Anlage: <%= link_to @mandate.attachment_file_name, get_attachment_mandate_path(@mandate), target: "_blank" %>
        </div>
      <% end %>
    </div>

    <%= render 'code' %>
    
    <div class="card">
      <div class="card-header h6">
        <%= link_to "Bearbeiten", edit_person_path(@mandate.client, {origin: mandate_path(@mandate)}), class: "float-right" if @mandate.client %>
        Mandant
      </div>
      <div class="card-body">

        <% if not @mandate.client.blank? %>
          <h4 class="person-name">
            <%= @mandate.client.name %>
          </h4>
          <%= render "people/details", person: @mandate.client %>
        <% else %>
          Kein Mandant
        <% end %>

      </div>
    </div>

  </div>
</div>

app/views/mandates/show.htmlp.erb
<%= render(:partial => 'mandates/mandate', :formats => [:html], locals: {mandate: @mandate}) %>